# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
julia:
  - 1.0
  - nightly
notifications:
  email: false
after_success:

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
